Portfolio
sodabarauf/main-portfolio pull request #1
Opened 2024-06-07 16:31 UTC by sodabarauf

this is capstone project of HTML and CSS, here I did these things:
-followed GitHub workflow.
-setup linters.
-added descriptive REABME.md file.
-added index.html and style.css file.
-added tags like section, div, img, button, input, textarea, form, p, h1, h3, i, and some other tags.
-added some styles.
-added @media query.

2024-06-07 19:43 UTC, faridafaqiri commented
Hi! dear sodaba 
your project has great design I really liked it.
it's also responsive and looks good at small screen.

2024-06-08 06:06 UTC, sodabarauf commented
> Hi! dear sodaba your project has great design I really liked it. it's also responsive and looks good at small screen.

thanks, from your feedback Farida Jan.

2024-06-08 06:10 UTC, sodabarauf commented
@ahzamir,
hello sir, I hope your being well.
my partner reviewed and provided me feedback, please review my project and get me your feedback.

2024-06-08 13:06 UTC, ahzamir requested changes
@sodabarauf 
![image](https://github.com/sodabarauf/main-portfolio/assets/96838030/118b92be-a6ff-476d-8fa4-ac398e8a6c9b)

- Well done you have done a great job implementing lots of requirements there are some small changes you need to add to your project inorder to get the final approval for your project.

- Check the comments below

2024-06-08 13:06 UTC, ahzamir commented on README.md
> +
- Remove this

2024-06-08 13:06 UTC, ahzamir commented on index.html
> +          <li><a href="#portfolio"><i class="fa-solid fa-paperclip"></i> portfolio</a></li>
Change the text to `Projects`

2024-06-08 13:06 UTC, ahzamir commented on index.html
> +          <button><a href="">live demo</a></button>
- Add the demo link for this project

![Screenshot 2024-06-08 145746](https://github.com/sodabarauf/main-portfolio/assets/96838030/d5731db7-a8fe-4af8-99e5-554f5dfc6dc2)

2024-06-08 13:06 UTC, ahzamir commented on index.html
> +        </div>
- Remove this project and instead add your survey form project here

![Screenshot 2024-06-08 145803](https://github.com/sodabarauf/main-portfolio/assets/96838030/7c529d7e-1dc0-45fe-88d3-0908e9060d9e)

2024-06-08 13:06 UTC, ahzamir commented on style.css
- Add a background color for your navbar header as when I scroll down it does not have a background color and it's not looking great.
![Screenshot 2024-06-08 145729](https://github.com/sodabarauf/main-portfolio/assets/96838030/db0100ac-e0a6-4097-ba4a-9cb6a8b078fb)

2024-06-08 17:41 UTC, sodabarauf commented
@ahzamir 
sir, thanks from provided feedback, I implemented all your feedback.
I hope this be acceptable.
thank you.

2024-06-15 07:45 UTC, merged